services:
  torznab-proxy:
    build: .
    container_name: torznab-proxy
    environment:
      - PROWLARR_BASE=http://192.168.1.4:9696
      - PROXY_BASE=http://192.168.1.4
      - SAFE_FILE_NAME=download.torrent
    ports:
      - "80:9797"
    restart: unless-stopped
